### ISSUE TITLE
Heavy gifs lag

### ISSUE THREAD

**Issue by gruvw** [kisstkondoros/gutter-preview#102]
Hi, I was working on a project today and my vs-code got laggy because of a heavy (~50mb) gif preview next to the line numbers...  
Could you maybe add a setting to disable gif rendering next to line numbers and maybe only display the first frame of the gif as a preview?  
That would be really nice thank you.

**Comment by kisstkondoros** [comment]
This option already exists
set 'gutterpreview.showImagePreviewOnGutter' to false
