### ISSUE TITLE
 Do not display pictures

### ISSUE THREAD

**Issue by W-ChenAMG** [kisstkondoros/gutter-preview#103]
![image](https://user-images.githubusercontent.com/37658262/109375847-e7243900-78fa-11eb-9a00-88782327e710.png)

**Comment by genaro-pinson-gh** [comment]
I got the same issue as well after doing the latest Visual Studio code update

**Comment by lyxsilence** [comment]
back 1.53.2

**Comment by dma550** [comment]
I just installed and find this behavior.  Is there a late breaking change to vscode that broke this?

**Comment by kisstkondoros** [comment]
There seems to be a breaking change in vscode, temp files can no longer be used to display images, unfortunately I have not found a workaround yet.

**Comment by W-ChenAMG** [comment]
I've been looking for it for a long time, but I can't find a solution.

**Comment by jnightingale** [comment]
Current recommendation would be to go back to 1.53.2 until a workaround is fixed?

**Comment by kisstkondoros** [comment]
Hopefully fixed in vscode-gutter-preview@0.27.1, should be available in a few minutes in the marketplace.

**Comment by genaro-pinson-gh** [comment]
Many thanks for the fix!

**Comment by dma550** [comment]
Thank you! Works very well now.
