### ISSUE TITLE
Question: keyboard-only preview?

### ISSUE THREAD

**Issue by tecunningham** [kisstkondoros/gutter-preview#105]
As far as I can tell there's no way of triggering a hover-preview with the keyboard only, you always have to use the mouse. Is that correct?

It would be nice to be able to trigger previews (either hover, or opening in another window) with the keyboard only. If anyone knows how to do that, I'd appreciate a pointer.

**Comment by kisstkondoros** [comment]
https://code.visualstudio.com/docs/getstarted/keybindings#_rich-languages-editing

Check the "Show hover" line for the shortcut
