### ISSUE TITLE
Is possible to edit the size of the image shown in the gutter?

### ISSUE THREAD

**Issue by ccaioccesar** [kisstkondoros/gutter-preview#109]
rt: https://stackoverflow.com/questions/67177537/is-possible-to-edit-the-size-of-the-image-shown-in-the-gutter

Is this possible?

**Comment by kisstkondoros** [comment]
No, there is no support for this in vscode afaik.

**Comment by ccaioccesar** [comment]
@kisstkondoros how to use the gutterpreview.Paths

I tried like:
`"@assets/*": ["C:\\Users\\CAIO\\Documents\\Github\\images\\"],
`
and in my file, i add `@assets/88587.png`
but it does not recognize the image

only recognize if i add the full path:
C:\Users\CAIO\Documents\Github\images\88587.png
