### ISSUE TITLE
How to use with alias name in vite.config.js？

### ISSUE THREAD

**Issue by Minori-ty** [kisstkondoros/gutter-preview#117]
jsconfig.json
![image](https://user-images.githubusercontent.com/79521943/129485275-de77448d-1b59-4cdb-b6a8-a40de65333df.png)
.vscode/settings.json
![image](https://user-images.githubusercontent.com/79521943/129485292-a4e81d32-7e8b-4988-bb91-94386919976b.png)
App.vue
![image](https://user-images.githubusercontent.com/79521943/129485310-855e76f9-1726-4c6b-87dc-7ad2d23bbd89.png)

**Comment by kisstkondoros** [comment]
Setting only the following should be enough:
```
"gutterpreview.sourceFolder": "./src/assets"
```

**Comment by Minori-ty** [comment]
> "gutterpreview.sourceFolder": "./src/assets"

When I set in the folder .vscode/settings.json,  it dosen't work. 
But when I set in the vscode's settings, it works! 
thanks you.
