### ISSUE TITLE
测试发现不支持BASE64格式的图片预览

### ISSUE THREAD

**Issue by dahuotu** [kisstkondoros/gutter-preview#122]
测试发现不支持BASE64格式的图片预览，可以升级支持一下吗

**Comment by dahuotu** [comment]
The test found that Base64 format picture preview is not supported

**Comment by dahuotu** [comment]
My English is not good

**Comment by kisstkondoros** [comment]
Can you provide an example data uri, which is not working?
Lines above 20000 characters are not scanned, maybe that is the cause?

**Comment by kisstkondoros** [comment]
Please open a new issue with more details
