### ISSUE TITLE
call as an object is possible?

### ISSUE THREAD

**Issue by Drckk** [kisstkondoros/gutter-preview#123]
![image](https://user-images.githubusercontent.com/31154275/148024940-388f6e96-7f9d-4cd9-ad4c-9d362e83658c.png)

**Comment by kisstkondoros** [comment]
It supposed to be working when setting ```"gutterpreview.enableReferenceLookup": true```, but the vscode API was changed in the meantime. Soon I'll release a new version in which this will work again.

Note that this lookup could be potentially expensive.

**Comment by kisstkondoros** [comment]
Fixed in vscode-gutter-preview@0.30.0, should be available soon

**Comment by Drckk** [comment]
> 

wow nice!!
