### ISSUE TITLE
Imgix images have incorrect file sizes

### ISSUE THREAD

**Issue by justinbhayes** [kisstkondoros/gutter-preview#125]
This extension works great for images that aren't using a CDN. However, when using it on an image that lives on Imgix and is using an optimization operation, the file size is incorrectly shown in Visual Studio Code. For example, both Chrome and the extension show this image is 525KB: https://nextivaweb.imgix.net/png/lpGVDT4-Hero.png. When using an imgix path such as https://nextivaweb.imgix.net/png/lpGVDT4-Hero.png?auto=format&w=480, Chrome has a file size of 22.3KB and the extension has a file size of 100.88KB.

**Comment by kisstkondoros** [comment]
I thought that maybe the CDN does some clever compression when delivering it to a browser vs when it is simply downloaded so I've tried curl:

```curl --output hero.png "https://nextivaweb.imgix.net/png/lpGVDT4-Hero.png?auto=format&w=480"```
```curl -H "user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36" --output hero_with_agent.png "https://nextivaweb.imgix.net/png/lpGVDT4-Hero.png?auto=format&w=480"```

and I also checked it in Chrome, like you said, Chrome shows ~22kb as download size, but the actual image is still exactly like the others downloaded with curl, when saved to the file system, it is still ~100kb.

I believe this CDN it still does some clever compression, but I can't figure out how could I configure the right request headers to get the same results...
