### ISSUE TITLE
It stopped working completely , no gutter & hover

### ISSUE THREAD

**Issue by awadkhaled** [kisstkondoros/gutter-preview#130]
Windows 10 
Vscode version 1.66
Extension version 0.30

**Comment by RaminBgrn** [comment]
i have got same problem too
is there any solution

**Comment by RaminBgrn** [comment]
after disable and enable it work .
but when i close vscode 
the extension stop working again

**Comment by maccabros** [comment]
Mine stopped working too,
Tried reinstalling, closing vscode, nothing works. 
Win11, extension ver 0.30

**Comment by mxp131011** [comment]
me too

**Comment by TheMedicus** [comment]
Windows 11 > vsc 1.72.2 > i have the same problem, it doesn't work without uninstalling and reinstalling the extension

**Comment by lborgman** [comment]
Same problem. Windows 10. 

Is there any alternative extension that can do preview on link hover?

**Comment by Hexi1997** [comment]
same, any progress?

**Comment by Hexi1997** [comment]
> same, any progress?

It worker now
