### ISSUE TITLE
mapping paths and alias

### ISSUE THREAD

**Issue by Minori-ty** [kisstkondoros/gutter-preview#135]
first, replace "@" with "$"
second, use "$xxx"

for example
```
    "gutterpreview.paths": {
        "$src": "${workspaceFolder}/src"
    },
```
then，you can use the alias for html
```
   <img src="src/assets/logo.png" alt="" />
   <img src="$src/assets/logo.png" alt="" />
```
![image](https://user-images.githubusercontent.com/79521943/177809646-2a4ee483-6157-444a-963b-a2a55bfdd7e8.png)

**Comment by Minori-ty** [comment]
but how I can use alias with "@"?  It don't work :(

**Comment by dusionlike** [comment]
Are you windows system?
If yes, #138 may be able to help you.
I released an [interim version](https://marketplace.visualstudio.com/items?itemName=dusion.vscode-gutter-preview-fork), you can try this.
then
setting.json
```
"gutterpreview.paths": {
    "@": "./src"
},
```
or
tsconfig.json
```
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"]
    }
  }
}
```

**Comment by mxp131011** [comment]
> Are you windows system? If yes, #138 may be able to help you. I released an [interim version](https://marketplace.visualstudio.com/items?itemName=dusion.vscode-gutter-preview-fork), you can try this. then setting.json
> 
> ```
> "gutterpreview.paths": {
>     "@": "./src"
> },
> ```
> 
> or tsconfig.json
> 
> ```
> {
>   "compilerOptions": {
>     "baseUrl": ".",
>     "paths": {
>       "@/*": ["./src/*"]
>     }
>   }
> }
> ```

`jsconfig.json` is unsuccessful, but  `tsconfig.json` is succeed

**Comment by mxp131011** [comment]
'gutterpreview.paths' can also

**Comment by Minori-ty** [comment]
> Are you windows system? If yes, #138 may be able to help you. I released an [interim version](https://marketplace.visualstudio.com/items?itemName=dusion.vscode-gutter-preview-fork), you can try this. then setting.json
> 
> ```
> "gutterpreview.paths": {
>     "@": "./src"
> },
> ```
> 
> or tsconfig.json
> 
> ```
> {
>   "compilerOptions": {
>     "baseUrl": ".",
>     "paths": {
>       "@/*": ["./src/*"]
>     }
>   }
> }
> ```

It's useful, thank you!

**Comment by Vsnoy** [comment]
> Are you windows system? If yes, #138 may be able to help you. I released an [interim version](https://marketplace.visualstudio.com/items?itemName=dusion.vscode-gutter-preview-fork), you can try this. then setting.json
> 
> ```
> "gutterpreview.paths": {
>     "@": "./src"
> },
> ```
> 
> or tsconfig.json
> 
> ```
> {
>   "compilerOptions": {
>     "baseUrl": ".",
>     "paths": {
>       "@/*": ["./src/*"]
>     }
>   }
> }
> ```

thanks，it works for me.

**Comment by xiangdongbu** [comment]
> "@": "./src"


![image](https://github.com/kisstkondoros/gutter-preview/assets/66773251/78db3dd5-cb91-4354-81e7-c8d366a633a5)

```
"gutterpreview.paths": {
    "@": "./src"
},
```
It doesn't work
