### ISSUE TITLE
Feature request:  custom filter for input string

### ISSUE THREAD

**Issue by LuisAyuso** [kisstkondoros/gutter-preview#137]
I find your tool extremely useful, but unfortunately, I use Qt and my paths are prefixed with "qrc:/". For example "qrc:/assets/icons/something.svg".
Could it be possible to add some sort of pattern or filter option so your tool identifies these strings as input as well? That would be awesome. 
I would be happy to test or help if this change is feasible.

**Comment by kisstkondoros** [comment]
Should be available in 0.32.1

Implemented a workaround to support protocol / scheme in the link recognizer, with that in place, "qrc:" is now a valid alias, which can be configured in "gutterpreview.paths".

```json
"gutterpreview.paths": {
  "qrc:": "assets"
}
```

![image](https://github.com/user-attachments/assets/98a86bcf-12f3-4f37-ab63-166b7859a1a1)
