### ISSUE TITLE
Language client is not ready yet

### ISSUE THREAD

**Issue by RenatoOwnZ** [kisstkondoros/gutter-preview#146]
Type: <b>Bug</b>

Image preview does not working in my vscode
"Activation Event:*
Activation Time:35ms
Uncaught Errors (33)
Language client is not ready yet
Language client is not ready yet
Language client is not ready yet
Language client is not ready yet
Language client is not ready yet
Language client is not ready yet
Language client is not ready yet
Language client is not ready yet
Language client is not ready yet
Language client is not ready yet
Language client is not ready yet
Language client is not ready yet
Language client is not ready yet
Language client is not ready yet
Language client is not ready yet
Language client is not ready yet
Language client is not ready yet"
Extension version: 0.30.0
VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:32:34.589Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5500U with Radeon Graphics          (12 x 2096)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.35GB (1.41GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by kisstkondoros** [comment]
Should not happen since 0.31.2
