### ISSUE TITLE
Only support image from ""

### ISSUE THREAD

**Issue by MonkeyKingMKY** [kisstkondoros/gutter-preview#154]
it seems that，this plugin only extract and identify image from text from "" now.
Is it possible to support from other style like :
`<xxx>test.png<xxx>`

**Comment by kisstkondoros** [comment]
It appears to be working just fine, please open a new issue if the issue persists
![image](https://github.com/user-attachments/assets/4b60d98c-bb3e-41a2-863f-0eefe8806309)
