### ISSUE TITLE
Can we add an option to show or hide the Referer header in HTTP?

### ISSUE THREAD

**Issue by toFrankie** [kisstkondoros/gutter-preview#155]
I'd like to propose adding an option that allows us to show or hide the Referer header in HTTP. The reason behind this is that some projects have restrictions on file access based on the Referer header to prevent unauthorized linking. However, when the setting is configured to "Domain only" and allows an empty Referer, accessing files within the editor becomes a challenge. Therefore, it would be really helpful if we could have a configuration option to specify the desired Referer. 

Thanks!

Here is the image with anti-leeching protection: 

https://mmbiz.qpic.cn/sz_mmbiz_png/s37uxK5D5wndKNh2MiclkZbGmhTp5zMFibTRpKp3MbaRxSUbM4groMPebwlYCfHUCYYRoJxEeA1RjzOMibc6SAhTg/640

![](https://mmbiz.qpic.cn/sz_mmbiz_png/s37uxK5D5wndKNh2MiclkZbGmhTp5zMFibTRpKp3MbaRxSUbM4groMPebwlYCfHUCYYRoJxEeA1RjzOMibc6SAhTg/640)

**Comment by toFrankie** [comment]
After checking the source code, I found that it was not unauthorized linking, but the image link did not meet the requirements of `acceptedExtensions`, so it was not displayed.

- [server.ts](https://github.com/kisstkondoros/gutter-preview/blob/master/src/server/server.ts#L162)
- [acceptedExtensions.ts](https://github.com/kisstkondoros/gutter-preview/blob/fa124f5758d8e48ba4434e736167b3bc3429862b/src/util/acceptedExtensions.ts#L1)

I plan to submit a PR to add a configuration item to support image links without extensions.

For example: https://mmbiz.qpic.cn/sz_mmbiz_png/s37uxK5D5wndKNh2MiclkZbGmhTp5zMFibTRpKp3MbaRxSUbM4groMPebwlYCfHUCYYRoJxEeA1RjzOMibc6SAhTg/640

**Comment by kisstkondoros** [comment]
Thanks!
