### ISSUE TITLE
Occasionally an error is reported during startup

### ISSUE THREAD

**Issue by xiangdongbu** [kisstkondoros/gutter-preview#156]
[Error - 13:26:23] Starting client failed
TypeError: Cannot read properties of undefined (reading 'on')
    at r (/Users/bu/.vscode/extensions/kisstkondoros.vscode-gutter-preview-0.30.0/dist/extension.js:2:237983)
    at new Promise (<anonymous>)
    at /Users/bu/.vscode/extensions/kisstkondoros.vscode-gutter-preview-0.30.0/dist/extension.js:2:237511

**Comment by kisstkondoros** [comment]
Should not happen since 0.31.2
