### ISSUE TITLE
Support for .avif images?

### ISSUE THREAD

**Issue by Rod911** [kisstkondoros/gutter-preview#158]

**Comment by ramil-thrive** [comment]
Is there any update on this? 🤔

<img width="700" alt="image" src="https://github.com/kisstkondoros/gutter-preview/assets/132285107/2340391d-95e6-46c9-9e39-a9654f8b2bc7">

**Comment by rommelmamedov** [comment]
Opened PR with fix: https://github.com/kisstkondoros/gutter-preview/pull/159

**Comment by kisstkondoros** [comment]
Published with vscode-gutter-preview@0.31.0.
