### ISSUE TITLE
Custom hovered image size?

### ISSUE THREAD

**Issue by V0idk** [kisstkondoros/gutter-preview#16]
i like this extension and use it to peek image, but it seems too small.
![image](https://user-images.githubusercontent.com/17514799/43079815-b40b20fa-8ec0-11e8-8bec-fed1942183a0.png)

**Comment by kisstkondoros** [comment]
vscode-gutter-preview@0.13.0 was just released with a new configuration property which allows changing the maximum height for the preview.
Please note that it might not work well above ~200 since vscode also applies a maximum height for the hover widget. AFAIK that can not be modified.
