### ISSUE TITLE
Excessive crop

### ISSUE THREAD

**Issue by SocietyReboot** [kisstkondoros/gutter-preview#171]
Your extension is **extremely** useful to me, BUT:

1. About 40% of the default height of the preview pane is wasted for a few lines of info that could be shown on the same line.
2. The remaining default space aspect practically doesn't suit any image.
3. The pane is not adapted to the image's aspect ratio + the info space, to show the full image.
4. There is no option to change the default height in settings.

![image-preview](https://github.com/user-attachments/assets/e34afce7-70e9-40ef-84ff-09b84d1f7935)

That makes default preview unusable in most cases. 
Locating an image link and adjusting the height everytime after starting VSCode, is anything but convenient.

So I suggest that the pane should follow the image's aspect ratio + the space need for the info in order to always show the image in full, or at least provide an option to change the default height.

Thanks, and keep up the good work!

**Comment by kisstkondoros** [comment]
There is no way unfortunately for any extension to control the hover widget size.
There are already issues reported to vscode about this, e.g.:
https://github.com/microsoft/vscode/issues/149191

Closing
