### ISSUE TITLE
Bug on vscode 1.27.2 x64 -  windows 10  x64 - 1803

### ISSUE THREAD

**Issue by GrosBourrin** [kisstkondoros/gutter-preview#20]
Not working on this vscode version. i clean-uninstalled vscode with some 3rd part uninstaller (bcuninstall, i have used iobit uninstaller too) , reinstalled it but nothing more to make it work, i have your last version 0.14.2 but not working better :/  i have verified the links of my pictures and they're fine, all is in a good place... not a lot of other extensions added except some themes

**Comment by kisstkondoros** [comment]
I've just rechecked it, for me it works without any problems:
![image](https://user-images.githubusercontent.com/14231157/45943757-e7ac9d00-bfe7-11e8-9698-8a12b3fb8310.png)

The windows version is not exactly the same but I suppose it has nothing to do with the problem:
```
OS Name:                   Microsoft Windows 10 Enterprise Evaluation
OS Version:                10.0.17134 N/A Build 17134
```

Could you provide some more details?
Folder structure, image type, example images, etc...
Perhaps a minimal setup where the problem occurs?

**Comment by GrosBourrin** [comment]
parameters user : 
{
    "editor.fontFamily": "Roboto Mono, Fira Sans, Consolas, 'Courier New', monospace",
    "editor.fontLigatures": true,
    "window.titleBarStyle": "custom",
    "workbench.iconTheme": "vscode-icons",
    "workbench.colorTheme": "Horizon",
    "editor.fontSize": 15,    
    "gutterpreview.showimagepreviewongutter": true,
    "gutterpreview.sourcefolder": "src",
    "editor.minimap.maxColumn": 100
}
workspace params  : 
{
    "workbench.iconTheme": "vscode-icons"
}
snapshot : 
[https://imgur.com/ojWGKbO](url)

the files ared in the same folder as the css files.
This is a CSS theme for firefox, in the chrome folder of the profile where all the 
attached files are. the theme works correctly and finds the image files (png, jpg, and svg) normally but the exension doesn't seem to work properly as expected, it worked fine since the 1.27.2 version x64  of vscode under windows 10  1803 x64 . They did 2 installation versions for windows : one in the usual path, and the other one for a user folder. i tried both version (with a clean-unistall with bcuninstaller) but i is the same bug ! 

Sorry if my english is not very good, i'm french, and froggies as i am are not very good at english language lol.

Anyway, for resuming, pic files are in the same folder of the CSS file, and as i said it worked since the new version of vscode... and i like your extension, it's very useful

**Comment by kisstkondoros** [comment]
Thanks for the detailed report!
I'll look into it soon!

**Comment by kisstkondoros** [comment]
Version 0.15.1 was just published (it's not yet available in the market for some reason), but once it will I hope it will fix this problem as well.

**Comment by GrosBourrin** [comment]
Still not working ! perhaps it comes from vscode 1.27.2 itself, i dunno, that's strange

**Comment by kisstkondoros** [comment]
I have the same version as you do, there must be something else...

**Comment by kisstkondoros** [comment]
Double checked it using the following environment:
```
> vscode --version
1.27.2
f46c4c469d6e6d8c46f268d1553c5dc4b475840f
x64
```
```
> systeminfo
OS Name:                   Microsoft Windows 10 Enterprise Evaluation
OS Version:                10.0.17134 N/A Build 17134
```
I've even applied all the configuration you have, and still... works just fine for me.

**Comment by GrosBourrin** [comment]
doesn't work much :/ too bad, i installed, reinstalled it several times, cleaning with ccleaner then bleach bit, nothing more i hate that ! maybe one day i'll find the trick

**Comment by GrosBourrin** [comment]
all my extensions worked correctly together, several themes and the other didn't corrupted the others.  all my pics (gif, jpg, png and base64 lines) are correctly supported by your extension but i just noticed one thing is that my gutter has shrinked ! don't know why, perhaps it's the reason why your extension can't display pics in it. how to recover or change the width of this gutter? is there a command or param to fix ?

**Comment by kisstkondoros** [comment]
I'm sorry to hear that it is not working for you, but I suspect it has something to do with some other extension chaning the width of the gutter.
As I said earlier I've tested it within a windows 10 vm with nothing but this extension installed and it worked properly.

If this problem is independent of other extension (so a real bug in my extension) then it will pop up again.

**Comment by GrosBourrin** [comment]
about gutter witdh , it that was a problem with another extension, but the principal problem persists, i'll explore all the file tree to find some folders and preferences left by uninstallation of vscode to clean it totally then reinstall it another time but i dunno what's the problem ! damn ! i love your extension :/

**Comment by GrosBourrin** [comment]
i re-open the conversation because i noticed  some odd things  : 

- i splitted my css file in modules that i import as @import"..... .css"; and noticed that the extension works again for this files

- the odd thing is that if i leave all my tabs opened the extension works only few instants when i jump in another tab and finishes to work i have to restart vscode, i really think it's a problem of memory management (that's my opinion).

- i have raised up the mem number in the prefs but nothing make it work again 

- when i open a css files it keeps working only if i have one tab opened

so : is it a problem of memory used by vscode ? what do you suggest about that ? for info i have 8Go or memory installed on my comp
