### ISSUE TITLE
[Question] Would this method possibly work for another extension

### ISSUE THREAD

**Issue by tecosaur** [kisstkondoros/gutter-preview#23]
Hello,

First things first, I'm going to admit that I'm not actually a user of this extension. Rather I'm interested if you might have an idea if what you've used here could be applied to something somewhat similar - namely previews of maths blocks for the extension [LaTeX-Workshop](https://github.com/James-Yu/LaTeX-Workshop) which I have a vested interest in.

Ideally, I'm hoping to implement something like [this](https://atom.io/packages/preview-inline). Since from a _having-inline-element-appear_ point of view this seems to be the closest thing - I thought it would be worth asking you whether you think something like this would be possible, and if so whether you would have any pointers.

Thanks!
tecosaur

**Comment by kisstkondoros** [comment]
Hi,

I think it could be implemented in a similar fashion.
The key things are the followings:
- create a *language server* (child process)
- register a callback on it which parses the input and gives you the text ranges your hover provider would operate on, and possibly also an image
- when that is done the *language client* has all the information it needs to provide the preview

You can also clone this repo and adjust it for your needs and publish it as a separate extension, however I would recommend to contribute to the mentioned LaTeX extension instead.

Also please check the vscode API:
https://code.visualstudio.com/docs/extensionAPI/vscode-api
and the samples they provide:
https://github.com/Microsoft/vscode-extension-samples

Have fun!
