### ISSUE TITLE
Bug on vscode 1.27.2 x64 - windows 10 x64 - 1809 (the story so far)

### ISSUE THREAD

**Issue by GrosBourrin** [kisstkondoros/gutter-preview#24]
i re-open the conversation because i noticed some odd things :

  -  i splitted my css file in modules that i import as **@import"..... .css"** and noticed that the extension works again for these files

The odd thing is that if i leave all my tabs opened the extension works only few instants but when i jump in another tab and it finishes to work and i have to restart vscode, i really think it's a problem of memory management (that's my opinion).

 -   i have raised up the mem number in the prefs but nothing better...

 -   when i open a css files it keeps working only if i have one tab opened.

finally : is it a problem of memory used by vscode ? what do you suggest about that ? for info i have 8Go of memory installed on my PC window

**Comment by kisstkondoros** [comment]
I think it has nothing to do with the available memory (it shouldn't). I'll look into it

**Comment by kisstkondoros** [comment]
Tested it again, on linux, on windows, it works fine for me.

It would be nice to have some more details.
Please provide a Minimal, Complete, and Verifiable example. (https://stackoverflow.com/help/mcve)

**Comment by GrosBourrin** [comment]
here are some screenshots of how it does on my pc ! 
Vscode 1.28 x64 windows 10 x64 1809
8 Go ram
Nvidia GTX 745 drivers updated

![2018-10-09_07h51_33](https://user-images.githubusercontent.com/40931468/46649445-5ddd0200-cb99-11e8-949a-16612c2ff237.png)
![2018-10-09_07h52_38](https://user-images.githubusercontent.com/40931468/46649449-60d7f280-cb99-11e8-8403-511e7782e540.png)
![2018-10-09_07h58_07](https://user-images.githubusercontent.com/40931468/46649450-62a1b600-cb99-11e8-95f5-f8bb6ca7a0be.png)

**Comment by kisstkondoros** [comment]
So, apparently the data uri support was entirely broken, I've fixed that in the latest version (0.15.2).

For the last issue, I have no idea... What happens there exactly? Did I understand it correctly that until you have only one tab open it works fine but if you open another one it breaks? (could it be that it was alos the data url issue?)

**Comment by GrosBourrin** [comment]
that's right ! :/ loss of uri data, i'll try the new version and tell you if it works

**Comment by kisstkondoros** [comment]
Version v0.15.3 was just released please give that a try (This is getting ridiculous sorry for all the troubles).

Since the recognizers are driven mainly by regular expressions (and they are costly) I had to introduce a maximum for the processed line length  (20.000 characters at the moment). If not all data uris are working, this might be the reason for it (this is new in v0.15.3)

I hope it'll work fine now.

P.S.: The reason that it only worked on one tab was that the recognizers were still processing the previous tab's content. This was also addressed in v.0.15.3
