### ISSUE TITLE
Don´t work :(

### ISSUE THREAD

**Issue by designerbyron** [kisstkondoros/gutter-preview#25]
- Extension Name: vscode-gutter-preview
- Extension Version: 0.15.1
- OS Version: Windows_NT x64 10.0.17134
- VSCode version: 1.28.0

 We have written the needed data into your clipboard. Please paste:
please :( help not run...

**Comment by kisstkondoros** [comment]
![screenshot 2018-10-08 20 14 37](https://user-images.githubusercontent.com/14231157/46626171-cc3ca880-cb36-11e8-84b0-1cb2155ab90c.png)

Works for me just fine, under linux and also under windows 10 ( exact version: 10.0.17134 Build 17134)

It would be nice to see more details other than it doesn't work...
Please try to provide a Minimal, Complete, and Verifiable example (https://stackoverflow.com/help/mcve)

**Comment by designerbyron** [comment]
After installing and uninstalling the extension several times I tried to restart the PC and until then I managed to see if it worked ... thanks for being pending, I quite like this extension

👍
