### ISSUE TITLE
Showing image if file selected in editor (especially for svg)

### ISSUE THREAD

**Issue by mmc41** [kisstkondoros/gutter-preview#3]
Would love if the gutter could also preview svg images when the file is selected ?

**Comment by kisstkondoros** [comment]
Could you please elaborate this? I don't understand what do you mean by the file is selected.

**Comment by mmc41** [comment]
If I select a SVG source file in the VS tree view of files it shows the source code only, so I can not see how it looks like. If I select an PNG file it will show the image instead. If the gutter could preview the svg image when selecting a SVG source file.

**Comment by kisstkondoros** [comment]
https://marketplace.visualstudio.com/items?itemName=cssho.vscode-svgviewer better for this use IMO

**Comment by mmc41** [comment]
I tried the SVG extension, but it is not so good.

**Comment by kisstkondoros** [comment]
try this 😃  https://marketplace.visualstudio.com/items?itemName=kisstkondoros.svgpreview

**Comment by mmc41** [comment]
A much better plugin. I have installed this one instead :-) 
I still have to manually select preview to see the preview though. Is it possible to toggle what is done by default (text editor with source or preview)?
Also, it might be a good idea to display warnings/errors if the svg source contain javascript inside so the JS is not executed on preview. Browsers should ignore those, but they might be misused for evil purposes.

**Comment by kisstkondoros** [comment]
I fear that is out of scope for extensions

**Comment by mmc41** [comment]
When I click on a png image, the image is shown by default - not the binary source. It would be great if the same thing can be done for svg. Are you saying that VS does not allow extensions to specify if the editor or something else is clicked when a file is selected ?

**Comment by kisstkondoros** [comment]
At least I can't seem to find any way to do so

**Comment by mmc41** [comment]
Eclipse has a concept of views and default views - where one can open a file in a specific view by right-clicking. VS does not seem to have that yet. Not much interesting happens if I right click.
