### ISSUE TITLE
Multi-preview ?

### ISSUE THREAD

**Issue by GrosBourrin** [kisstkondoros/gutter-preview#30]
Is it normal ? (lol)
word wrap on
![2018-10-26_14h59_15](https://user-images.githubusercontent.com/40931468/47571131-1f389d00-d938-11e8-8b50-3575ce77afc7.png)

word wrap off
![2018-10-26_16h07_24](https://user-images.githubusercontent.com/40931468/47571641-53f92400-d939-11e8-8e09-6b59d1acda19.png)

**Comment by kisstkondoros** [comment]
Thanks for the issue report, it is fixed in version 0.16.3, which was just released.

**Comment by GrosBourrin** [comment]
works good
