### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Eugene-Musika** [kisstkondoros/gutter-preview#35]
- Issue Type: `Performance`
- Extension Name: `vscode-gutter-preview`
- Extension Version: `0.16.5`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.30.2`

[kisstkondoros.vscode-gutter-preview-unresponsive.cpuprofile.txt](https://github.com/kisstkondoros/gutter-preview/files/2804039/kisstkondoros.vscode-gutter-preview-unresponsive.cpuprofile.txt)

**Comment by kisstkondoros** [comment]
This is not the first time of receiving such an issue report, see #32 and #31 but I have no clue what could potentially cause this.

Could you elaborate on this a bit? How much extensions you have? Could you please list them? How much tabs were open when this have happened?

The cpu profile shows it was only occupied with my extension for 38ms. Can we believe that?
I have the feeling that the profile is just plain wrong. If so I would like to delegate these issue reports to the vscode repo or at least ask for some help.

**Comment by kisstkondoros** [comment]
Could you please check this again with the new vscode version? It seems they've improved the logs.
