### ISSUE TITLE
The "path" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by Yzrsah** [kisstkondoros/gutter-preview#38]
I am getting hundreds of errors in Developer Tools console log:

```
mainThreadExtensionService.ts:50 TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined

at Timeout.throttleIds.(anonymous function).setTimeout [as _onTimeout] (kisstkondoros.vscode-gutter-preview-0.17.2/out/src/decorator.js:19:17)
```

I try to keep my console log clear of extension errors so I can resolve problems or performance issues with extensions, so I had to disable this extension for now

**Comment by kisstkondoros** [comment]
Thanks for reporting the problem, a new version is available in the market which hopefully resolves this.
Sorry for the inconvenience.
