### ISSUE TITLE
Conflict with another Extension

### ISSUE THREAD

**Issue by ridesirat** [kisstkondoros/gutter-preview#40]
Hi @kisstkondoros 
I was having a problem with Live server and Live Sass extensions from @ritwickdey (https://github.com/ritwickdey/vscode-live-server/issues/285#issuecomment-462728705)
and I realized it appears to be from a conflict with yours.
I tried all solutions in @ritwickdey's issue and none worked. Then I noticed in the console there was an error pointing to your extension. I disabled it and now @ritwickdey's is ok.
I'm just telling you this because I have to choose between the two and I think it was correct to let you know.
Hope you can manage it with @ritwickdey  :)
All the best.
And I hope it was helpfull

**Comment by kisstkondoros** [comment]
Thanks for reporting the problem.

Could you please retest it with 0.17.4?

I've tested it in combination with the mentioned extension, and for my tests everything worked fine, therefore I'll close this ticket.

If the problem still present please respond to this ticket or create a new one.

**Comment by FelesNoctis** [comment]
I was also experiencing this conflict, and can confirm that 0.17.4 seems to have resolved the issue!

**Comment by ridesirat** [comment]
Just tested it. It's ok!
Thanks.
