### ISSUE TITLE
[suggest] double click to win folder

### ISSUE THREAD

**Issue by djmisterjon** [kisstkondoros/gutter-preview#43]
Hi, i luve this plugin, and i just want add a little suggest here, i dont know if possible but do you think your can add a option for when double click on the image, open the window navigation to the current folder ?
![image](https://user-images.githubusercontent.com/24865815/54095406-91f16480-437d-11e9-9bb8-50ba19546e14.png)

it just a suggest for get some more productivity when we need to check in the folder.
thanks a lot friend.

**Comment by kisstkondoros** [comment]
A link to reveal the file in the side bar was added to the hover message in version 0.18.0. I hope you'll make use of it ;-)

**Comment by djmisterjon** [comment]
ho shit this is a better idea, i luve it, thanks my friend, this is awesome!
