### ISSUE TITLE
[bug] I can't put breakpoints when there is a image preview on that line

### ISSUE THREAD

**Issue by mirkancal** [kisstkondoros/gutter-preview#44]
Title is explaining the issue. I can't put breakpoints behind that thumbnail images.

**Comment by kisstkondoros** [comment]
Thanks for the issue report!

This is unfortunate indeed, but I have no influence on that behavior: see Microsoft/vscode#5923 for furher details.

Until the linked issue is fixed, the following configuration can be applied to hide the preview images on the gutter:
```json
"gutterpreview.showImagePreviewOnGutter": false
```
