### ISSUE TITLE
Support for .ico files?

### ISSUE THREAD

**Issue by Joey79100** [kisstkondoros/gutter-preview#45]
Hey!
We're using **.ico** files for most icons in a CSS file of a web application. However, this extension doesn't show preview for **.ico** files (VSCode can display them if you **Ctrl**+**Click** them). Other common formats work just fine.
Would it be possible to add support for **.ico** files? Thank you.

**Comment by kisstkondoros** [comment]
I'll have a look at it later today, but ico files could contain more than one image and I possibly have to convert them, so no promises.

**Comment by kisstkondoros** [comment]
Apparently it just worked by adding "ico" to the list of supported types :smile: 
Of course the support is very basic, but I hope it covers most of the use cases (e.g. multiple layers are not supported)

Version 0.19.0 (which contains this) is in the market already :fireworks:

**Comment by Joey79100** [comment]
Oh wow that was fast! It looks like it takes the biggest layer instead of the one that has the closest resolution to which it is displayed, but it's more than enough (it's just a preview after all). Thank you! 😄
