### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by dreamoo** [kisstkondoros/gutter-preview#46]
- Issue Type: `Performance`
- Extension Name: `vscode-gutter-preview`
- Extension Version: `0.18.0`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.33.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\dreac\kisstkondoros.vscode-gutter-preview-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by kisstkondoros** [comment]
Please attach the file mentioned in the description.

**Comment by kisstkondoros** [comment]
As this issue has popped up several times without any real clue about what is actually going on (or 100% pointing out another extension) I close this ticket for housekeeping purposes.

If you really do have a perfomance issue please open a new ticket explaining that in detail and if possible provide a project setup where I can reproduce the issue, unfortunately the cpuprofile does not tells me too much anyway (usually).
