### ISSUE TITLE
blade compatibility

### ISSUE THREAD

**Issue by azc666** [kisstkondoros/gutter-preview#47]
laravel 5.8
resources/views/file.blade.php does not show gutter preview
public/file.html shows gutter preview (identical html)

**Comment by kisstkondoros** [comment]
You can configure the 'public' directory to be scanned by setting the configuration property like this.
```json
"gutterpreview.sourceFolder": "public"
```
or by setting it in the ui like this
![image](https://user-images.githubusercontent.com/14231157/56513864-0c440580-6534-11e9-9ca7-1ce2cd681a79.png)

I've tested it with https://github.com/azc666/dev and it worked fine, I hope this helps.

**Comment by azc666** [comment]
Hey Tamas,

So public and it’s subdirectories show fine.
How can I include multiple folders?
I use laravel and would like the extension for views in resources too :)
tried to separate by commas, semicolons but can’t get it to work.

Thx for making this available!

Allen
--------------------------------
Allen Cohen, President
Graphics + Design
Carter Printing Company
1111 W. Cass Street
Tampa, FL 33606
813-254-9444
allen@g-d.com <mailto:allen@g-d.com>
www.g-d.com <http://www.g-d.com/>

**Comment by azc666** [comment]
Tamas,

My apology, This does work! I think I was trying to preview a “.pdf” !!

Thanks for your work!

Allen
--------------------------------
Allen Cohen, President
Graphics + Design
Carter Printing Company
1111 W. Cass Street
Tampa, FL 33606
813-254-9444
allen@g-d.com <mailto:allen@g-d.com>
www.g-d.com
