### ISSUE TITLE
Does not show icons and images in PHP documents with HTML content

### ISSUE THREAD

**Issue by COD3BREAK3R** [kisstkondoros/gutter-preview#49]
It does not preview images if they have not been inserted into Visual Studio Code

**Comment by COD3BREAK3R** [comment]
If you have a document already created and with images inside that were already included and you want to see the preview when passing the cursor, it will not show them to you, it only shows the preview of the images inserted inside VS

**Comment by kisstkondoros** [comment]
I'm not sure If I get it right but the image urls might be relative to the document, to the workspace etc. If the image url is relative to e.g. the workspace location, but only a single document is opened (in that case there is no workspace folder) the image path would not be resolved correctly.

Closing for now, but please file a new issue if the problem persists, and make sure you provide the project layout (folder structure, file names) or even better a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)
