### ISSUE TITLE
Maybe support preview image in markdown file

### ISSUE THREAD

**Issue by ngtrian** [kisstkondoros/gutter-preview#5]
In Markdown, image preview don't show

**Comment by kisstkondoros** [comment]
Check version 0.9.0 😉

**Comment by ngtrian** [comment]
Seem still not working!

**Comment by kisstkondoros** [comment]
Could you please provide an example markdown file?

In e.g. the [README.md](https://github.com/kisstkondoros/gutter-preview/blob/master/README.md) it is working for me:
![image](https://cloud.githubusercontent.com/assets/14231157/23873757/69e84a44-0833-11e7-8016-707ccdc4489a.png)

**Comment by ngtrian** [comment]
can you check file:

[thiet-lap-co-ban-nopcommerce.md](https://gist.github.com/ngtrian/1f8afad070d87c7c014b7fb3daa3e687#file-thiet-lap-co-ban-nopcommerce-md)

**Comment by kisstkondoros** [comment]
Works with that file as well: 
![image](https://cloud.githubusercontent.com/assets/14231157/23886872/7bb51932-087e-11e7-9f8a-10e9fdc5bb6e.png)

Which vscode version you are using?

**Comment by ngtrian** [comment]
I'm using lastest version 1.10.2

![image](https://cloud.githubusercontent.com/assets/4327817/23887500/e430884e-08b4-11e7-9bc9-d29d74a2f3e8.png)

**Comment by kisstkondoros** [comment]
It turned out to be a missing null check, thanks for the issue report!
Version 0.9.1 should be available now in the market (this contains the fix).

**Comment by ngtrian** [comment]
Great! Thank for plugin
