### ISSUE TITLE
Reveal in Side Bar button does not work

### ISSUE THREAD

**Issue by COD3BREAK3R** [kisstkondoros/gutter-preview#54]
The name says it all, I'm in VS Code 1.35 using Windows 10 1803 and the button that does not work

**Comment by kisstkondoros** [comment]
For me it does work...

Could you please provide more information other than it does not work?
There might be some specialities in your workspace which prevents it from working.

Closing for now, but feel free to reopen / file a new one.

**Comment by COD3BREAK3R** [comment]
> For me it does work...
> 
> Could you please provide more information other than it does not work?
> There might be some specialities in your workspace which prevents it from working.
> 
> Closing for now, but feel free to reopen / file a new one.

@kisstkondoros 

In my case it was inside an HTML document if I remember correctly and in PHP I think I tried it too. Later I'll try again to confirm the details.
