### ISSUE TITLE
New Idea

### ISSUE THREAD

**Issue by Highter87** [kisstkondoros/gutter-preview#56]
I'd love to see the base64 data mapping in the gutter, which I mean, see below

```
.imgFon {
	background: url(data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTYiIGhlaWdodD0iMTYiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PHJlY3QgeD0iLjI1IiB5PSIuMjUiIHdpZHRoPSIxNS41IiBoZWlnaHQ9IjE1LjUiIHJ4PSI3Ljc1IiBmaWxsPSIjZmZmIiBzdHJva2U9IiM4RThFOTMiIHN0cm9rZS13aWR0aD0iLjUiLz48L3N2Zz4=) no-repeat center center; width: 16px; height: 16px;
}
```

**Comment by kisstkondoros** [comment]
You can surround the url with single or double quotes and it will work.

**Comment by akendy** [comment]
It's not working on hover.

![Screen Shot 2019-07-17 at 15 10 19](https://user-images.githubusercontent.com/25534713/61399685-0f396280-a8a5-11e9-9f3f-87c70aadf5a6.png)

**Comment by kisstkondoros** [comment]
Will be fixed by #58

**Comment by rafaelkendy** [comment]
base64 image preview is not working

**Comment by DATEx2** [comment]
7 years later and base64 images is still not working
