### ISSUE TITLE
Support for `currentColor` setting

### ISSUE THREAD

**Issue by dimitarnestorov** [kisstkondoros/gutter-preview#59]
Would be awesome to be able to set `currentColor` to be anything but black in settings so that there's more contrast between dark themes and SVGs that use `currentColor`. Depending on my viewing angle the following preview can be invisible.
![image](https://user-images.githubusercontent.com/8790386/61481171-3c1e7000-a9a0-11e9-80d1-b5fa25efc669.png)

**Comment by kisstkondoros** [comment]
Hacked into v0.20.0, should be available in the market in a couple of minutes :smile: 
You can configure the `currentColor` css property by the new configuration property `gutterpreview.currentColorForSVG`. It's default is `white` as the default vscode theme is a dark one.

I hope you'll find it useful!

Please give feedback if something feels or works odd, as this is a huge hack (IMO)!

**Comment by dimitarnestorov** [comment]
![image](https://user-images.githubusercontent.com/8790386/61562236-8a537200-aa79-11e9-8fd3-0bd91a0e648d.png)
Much better! Thanks!
