### ISSUE TITLE
Preview local Image in frame ?

### ISSUE THREAD

**Issue by djmisterjon** [kisstkondoros/gutter-preview#6]
**Hi friend,** 
I'm desperately looking for a plugin, which will allow me to simply visualize a reference to an image.

I have to build a huge database.
Similar to Json, but in JS.
Do you have an idea if a plugin that would allow me to visualize a local image in a frames exists?

I took the time to make a small image to show my need.
I will be really happy if, through your experience, you will have a small plugin that will allow this feature.
I would like to see a local image when my mouse passes over a link that references a local image.

Preview
http://imgbox.com/sHLBF4kF
![vsc-plugin-iomage-preview](https://cloud.githubusercontent.com/assets/24865815/24588940/d56b66b8-179f-11e7-8fd3-6116607f3f51.jpg)

Do you have an idea if your plugin can do something similar, or know you a plugin that could have this feature?

Thank you very much for your help.

**Comment by kisstkondoros** [comment]
In this format it would be a parsing overhead.

If you don't insist the hover message to show the image there are several alternatives in the market.
A quick search led me to: https://marketplace.visualstudio.com/items?itemName=kevin-felichko.open-under

Hope this helped
