### ISSUE TITLE
Preview image from Settings Class

### ISSUE THREAD

**Issue by hossameldinmi** [kisstkondoros/gutter-preview#60]
in **Dartlang** How can I preview when using **const property** of a class like **Settings Class**,
```
class Images{
    static const String splash='assets/images/splash.png';
}
```
and use it like this
`AssetImage(Images.splash), fit: BoxFit.cover),`

**Comment by kisstkondoros** [comment]
So the 'assets/images/splash.png' would be looked in several places as it is a relative path.
Is it next to the current file? Is it in the workspace/project root? There is also a configuration option `gutterpreview.sourceFolder` which can be used to define an additional source folder (by default it is `src` but you might have a different project layout).

If you couldn't make it work or of something doesn't work as you would expect could you please point to a repo where this could be checked?

Oh and I don't know what would you expect in the `AssetImage(Images.splash), fit: BoxFit.cover),` part. Would you expect it to be shown next to that line or smth. like that?

**Comment by hossameldinmi** [comment]
@kisstkondoros actually when hovering on `splash `prop in `Images` class it works and shows the image, but if I hover on `Images.splash` that referenced the real link from outside class it does not show anything.
briefly: 
 `static const String splash='assets/images/splash.png';` => show image,
`Images.splash` =>nothing appeared

**Comment by kisstkondoros** [comment]
I see, for that to work I would need to get the data out via a vscode api, the command `vscode.executeDefinitionProvider` looks promising, I'll look into it, but I see some troubles with that.

**Comment by kisstkondoros** [comment]
So a very hacky implementation was just shipped with version 0.21.0, I hope you'll find it useful! :fireworks:

**Comment by Gama11** [comment]
This change seems to be causing some major issues: https://github.com/kisstkondoros/gutter-preview/issues/62#issuecomment-519099244

**Comment by kisstkondoros** [comment]
@Gama11 Yes, thanks for reporting and linking the issues together!

@hossameldinmi If you like to experiment with the feature, you can turn the feature flag `gutterpreview.enableReferenceLookup` back by setting it to true.

As I've suspected this feature had sever performance issues, as the language server needs to resolve all references on demand on basically each user interaction.
While it caused no trouble (in perhaps a non representative workspace) for me with dart and typescript, for other languages it did (e.g. for Haxe in the linked issue).

**Comment by hossameldinmi** [comment]
@kisstkondoros Thanks for your awesome feature,
but I think it causes an issue #63 
![Screenshot (2)](https://user-images.githubusercontent.com/12272548/63079325-58311500-bf3e-11e9-856f-6c72e69035f6.png)

**Comment by kisstkondoros** [comment]
It seems it is unrelated, as there might be some changes in the latest vscode which affects the hover preview. I'm investigating this at the moment...
