### ISSUE TITLE
0.21.0 version will make vscode slowly

### ISSUE THREAD

**Issue by Moerj** [kisstkondoros/gutter-preview#62]
![QQ20190807-160512](https://user-images.githubusercontent.com/13795438/62605772-5f986300-b92d-11e9-8b7d-3a82070217bb.jpg)

vscode@1.36.1

Image Preview@0.21.0

OS: macOS Mojave 10.14.6

when I update Image Preview. It slow down my vscode.

such as code suggestions. Edit area scrollbar. It's getting slower.

When I disable this plug-in, everything was OK. 

Previous versions were also normal.

**Comment by Gama11** [comment]
I'm having similar issues. I think as of https://github.com/kisstkondoros/gutter-preview/commit/cc74b4bd4e1e17dc6c6d3d7f87294b1d0515694c, the extension is creating a ton of definition requests each time you scroll the page. It depends on the language implementation in question how bad this is exactly.

For Haxe for instance, processing individual definition requests is far from instant. Here's a visualization of all the requests that are getting queued up and how long it takes to process them:

![](https://i.imgur.com/rALa9xc.gif)

While the requests are getting processed, all other language features are blocked (code completion etc). Or in other words, this extension currently makes VSCode unusable.

**Comment by kisstkondoros** [comment]
Thanks for reporting the issue, the new feature was put behind a feature flag `gutterpreview.enableReferenceLookup` and it is turned off by default for now.
The fixed version, 0.21.1 was just published to the marketplace which should solve this without any further configuration on your side.

Sorry for the inconvenience.
