### ISSUE TITLE
Thumbnails stopped showing on hover

### ISSUE THREAD

**Issue by guralroman** [kisstkondoros/gutter-preview#63]
Thumbnails stopped showing on hover

![img-2019-08-13-14-36-04](https://user-images.githubusercontent.com/23074835/62938443-c0191b80-bdd7-11e9-88a6-a519cfaef36e.png)

Or is it my local error?

**Comment by kisstkondoros** [comment]
It is really strange, as the image size can be seen in the hover description...
I'll look into it

**Comment by kisstkondoros** [comment]
Are the images shown on the gutter (next ot the line numbers) correctly?

**Comment by guralroman** [comment]
Yes, it is displayed normally. Everything broke in the last update VisualStudiocode

![img-2019-08-14-06-18-21](https://user-images.githubusercontent.com/23074835/62992273-7f62e600-be5b-11e9-909a-4afd531e16ed.png)

**Comment by romantrs** [comment]
Same trouble
![image-preview_error](https://user-images.githubusercontent.com/18595966/63066263-903f5480-bf4c-11e9-8342-630bb12de9fb.png)

**Comment by hossameldinmi** [comment]
Same Issue
![Screenshot (2)](https://user-images.githubusercontent.com/12272548/63079155-ebb61600-bf3d-11e9-9fe8-1e33ae18cf9f.png)

**Comment by guralroman** [comment]
Specially checked such a problem occurs only on the updated version of VSC (1.3.7.0).
If you roll back to the previous one, everything works fine.
So the problem is not in my system, but in the module.

**Comment by zopad** [comment]
Bug only happens starting from 1.37.0 vscode

The tooltip shows a different embedded link, a temp file in the User/AppData/Local/Temp/ folder.

**Comment by kisstkondoros** [comment]
There might be some changes in vscode which I'm investigating at the moment, thanks for the input!

**Comment by kisstkondoros** [comment]
I've just published v0.22.2 to the marketplace, which should fix this for good...

Thanks to everyone for the collaboration!

**Comment by romantrs** [comment]
The error disappeared after updating vscode to 1.37.1. Now everything works as it should.
![image-preview_error--disappeared](https://user-images.githubusercontent.com/18595966/63139766-c9e28f00-c022-11e9-9523-b5b8df7d09aa.png)

**Comment by krupenja** [comment]
I am still seeing thin in VSCode 1.38.0. Any ideas?
