### ISSUE TITLE
hover img src has not effect in .vue files

### ISSUE THREAD

**Issue by Moerj** [kisstkondoros/gutter-preview#7]
![qq20170523-091539](https://cloud.githubusercontent.com/assets/13795438/26334566/94380cd4-3f98-11e7-9207-97fc04b6059b.jpg)

As the picture shows. Img preview on the left is ok. But cursor hover has no preview.

Image preview 0.9.1
OS: macOS Sierra
vscode 1.12.2

**Comment by kisstkondoros** [comment]
Version 0.10.0 is available including the fix for this issue. 🎆

**Comment by Moerj** [comment]
![qq20170612-015326 2x](https://user-images.githubusercontent.com/13795438/27013213-2d1f9eca-4f12-11e7-9de4-e917202e85cd.jpg)


@kisstkondoros It is not work on 0.10.0 !😰

**Comment by Moerj** [comment]
![qq20170612-020115 2x](https://user-images.githubusercontent.com/13795438/27013258-1534c0f0-4f13-11e7-910f-af9b30a66ce1.jpg)

Ok. I add Image suffix. It work. Thanks.

Can it fit suffix automatically?

**Comment by kisstkondoros** [comment]
Sorry but no, file extension should not be added automatically. In your case the image provider find the image based on the id in the url, if I would try to guess the file extension it would cause unnecessary overload for the target server. In general there could be multiple files with the same name but different extension, therefore it must be uniquely identified.

**Comment by Moerj** [comment]
I got it. Thanks very much!
