### ISSUE TITLE
Duplication of SVG's style tag renders code invalid

### ISSUE THREAD

**Issue by soulrelic616** [kisstkondoros/gutter-preview#70]
Hello,

First off, this extension is great and very useful.  Thank you!

The issue in question happens when working with SVG images that already have a style attribute set (this mainly happens with SVG's created with Adobe Illustrator or exported with Photoshop), the SVG has then two style tags making its markup invalid. Therefore  the SVG will not render within the extension.

Upon inspecting I found out this is being caused by the "gutterpreview.currentColorForSVG" configuration, which by default adds a white background to all SVG's when creating them, but even after leaving it empty it will still add a `background:` to the tag.

The solution would be writing an if statement to check if currentColorForSVG has been set, if empty don't add the tag for the element:

**src/util/imagecache.ts**

```
if (path.endsWith('.svg')) {
    const read = promisify(fs.readFile);
    const write = promisify(fs.writeFile);
    return promise;
    read(path)
        .then(data => {
            const original = data.toString('UTF-8');
            if (currentColorForClojure == "") {
                return original;
            } else {
                return original.replace('<svg', `<svg style="color:${currentColorForClojure}"`);
            }
        })
        .then(data => {
            return write(path, data);
        })
        .then(() => res(path))
        .catch(err => rej(err));
} else {
    res(path);
}
```
A temporary solution I have implemented in my local copy of the compiled extension can be found below:

**dist/server.js**

```
return new Promise(function (t, r) {
    if (e.endsWith(".svg")) {
        var i = f.promisify(u.readFile),
            o = f.promisify(u.writeFile);
        i(e).then(function (e) {
            if (n == "") {
                return e.toString("UTF-8");
            } else {
                return e.toString("UTF-8").replace("<svg", '<svg style="color:' + n + '"')
            }
        }).then(function (t) {
            return o(e, t)
        }).then(function () {
            return t(e)
        }).catch(function (e) {
            return r(e)
        })
    } else t(e)
})

```

I tried forking the repo and applying the fix myself but I'm afraid my VSCode extension knowledge is not as advanced yet :)

Please let me know your thoughts.

Thanks!

**Comment by kisstkondoros** [comment]
Sorry for the late fix, I wanted to fix it properly, but as always, things weren't as easy as I've expected (no access to DomParser / XmlSerializer in the 'server' part).

Anyway, if you configure the property ```currentColorForSVG``` to an empty string it should not mess up the svg.

Thanks for the issue report!
