### ISSUE TITLE
SVG doesn't appear in Visual Code 1.40.2 !

### ISSUE THREAD

**Issue by GrosBourrin** [kisstkondoros/gutter-preview#71]
title says all : nothing in gutter ! image preview 0.23.0
underline isn't hiding when i turn it off

![2019-11-27_06h04_25](https://user-images.githubusercontent.com/40931468/69695204-c9569b80-10db-11ea-8e56-100d6e32ff25.png)

**Comment by kisstkondoros** [comment]
Thanks for the issue report, could you please recheck with version 0.24.2?

About the underline: it is a default feature from vscode.

**Comment by kisstkondoros** [comment]
It could also potentially be related to #70, in case if the svg has a style attribute (the svg tag element literally) it could happen that it is not shown properly. If that is the case, please try to set the configuration property `currentColorForSVG` in the user config to an empty string.

I'll close this for now, feel free to reopen / file a new issue if it does not works out.

And sorry for the inconvenience.

**Comment by GrosBourrin** [comment]
> currentColorForSVG

it works with that ! thanks
