### ISSUE TITLE
reveal in explorer

### ISSUE THREAD

**Issue by djmisterjon** [kisstkondoros/gutter-preview#73]
Hi friend, first thanks you for your awesome plugin!.
Did you think you can also add a fast link for `reveal in explorer` ?
I know i can do it from vscode editor file explorer, but this can save me some time and get more productive.
In most case, i don't want open in vscode sideBar , but open in window explorer. :)

![image](https://user-images.githubusercontent.com/24865815/71549564-72b7d800-298d-11ea-87d8-4e53abafae5e.png)

_context: because all my files are sort inside folders and sub folder, so i have a lot of folders and subFolders hierarchy._
thanks

**Comment by kisstkondoros** [comment]
v0.25.0 was just published with this addition

**Comment by djmisterjon** [comment]
thank for your awesome work
