### ISSUE TITLE
I use dev remote plug to connect the remote server, and your plug didn't wok 

### ISSUE THREAD

**Issue by kangkang59812** [kisstkondoros/gutter-preview#74]
![F7D7A140-8DED-46B7-8D8F-96B1F949B0C3](https://user-images.githubusercontent.com/12228641/71715003-e3a63680-2e4a-11ea-8b6a-2ee63be53463.png)
The pic is saved on remote server.

**Comment by kisstkondoros** [comment]
This is strange, I've just checked it and it works well for me:

![image](https://user-images.githubusercontent.com/14231157/72752950-dc5d8780-3bc3-11ea-872f-4982264d1326.png)

![image](https://user-images.githubusercontent.com/14231157/72752885-b801ab00-3bc3-11ea-8dec-a502ce174898.png)


Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T15:04:31.999Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.0.0-37-generic snap

Could you please try it again with the latest versions of both the extension and vscode?

**Comment by kisstkondoros** [comment]
I'll reopen this if more details are provided.
