### ISSUE TITLE
Fully escaped Windows file path doesn't seem to work

### ISSUE THREAD

**Issue by hoangph271** [kisstkondoros/gutter-preview#75]
Here, if I don't escape the '\' after 'E:', gutter-preview works...!
![Capture](https://user-images.githubusercontent.com/39024711/72319548-04378180-36d2-11ea-8502-09f96fd07ee6.PNG)
But if I escape it, gutter-preview doesn't work...!
![Capture_2](https://user-images.githubusercontent.com/39024711/72319549-04378180-36d2-11ea-8b4d-e6d6dc8062dc.PNG)

**Comment by kisstkondoros** [comment]
I don't have access to a windows machine right now, so I can't test it, but I have the suspicion that some parts of the URI are allowed to be escaped while others are not (by some mechanism in the code).

Workaround:
I would like to suggest to just switch to '/' as delimiter, your code will also work on other OS' as well.

Could you elaborate on the usecase a bit please?

**Comment by kisstkondoros** [comment]
I'll close this until further details are provided.
