### ISSUE TITLE
Rendering inside the doc ref [request]

### ISSUE THREAD

**Issue by djmisterjon** [kisstkondoros/gutter-preview#76]
Hi friend, i have a little request enhancement.
Did you think you're able to allow preview image inside the vscode documentation box when hover mouse?

Something like this, see the reference doc box.
![image](https://user-images.githubusercontent.com/24865815/75835155-1fe30e00-5d8c-11ea-9e3c-40dfd677ab95.png)

thanks a lot for all your awesome work with this plugin.

**Comment by kisstkondoros** [comment]
Thanks for reaching out!

This is a good idea, but I don't think this is possible at the moment.

I think in your case (based on the screenshot above) the following will not help, but you can 
give it a try.
The ```gutterpreview.enableReferenceLookup``` flag enables the lookup to go one step ahead and collect image like uri-s from constant references.
