### ISSUE TITLE
Cannot to force it to work with aliases

### ISSUE THREAD

**Issue by chojnicki** [kisstkondoros/gutter-preview#77]
This extension works great to "normal" paths, but I cannot make it work with webpack aliases. It should work based on #48 #21 #36 

My jsconfig.json looks like this:

```
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "~/*": ["./*"],
      "@/*": ["./*"],
      "~~/*": ["./*"],
      "@@/*": ["./*"],
    }
  },
  "exclude": ["node_modules", ".nuxt", "dist"]
}

```

This is default content from Nuxt project. But I cannot see gutter preview. 
I also tried set this in settings.json - nothing. Also tried to make other aliases from issue in this repository for ex. "@assets/*": ["assets"] - nothing. After every change I restarted IDE.
So can You provide some working example?

![9513fcec2be1aead430ffb14368f2176](https://user-images.githubusercontent.com/34774522/76486070-903dff00-641e-11ea-8a2c-191cccd08bae.png)

**Comment by chojnicki** [comment]
Ok so I discovered that after renaming jsconfig.json to tsconfig.json everything works fine. Why is that so? Fine for me, I will stick with tsconfig, but based on docs it should work with both files. Any info?

**Comment by kisstkondoros** [comment]
Sorry for the inconvenience, I'll update the docs.

It's been a while since I've adjusted that part of the code, as far as I can tell, the possibility to configure this with jsconfig was removed together with the typescript dependency.
In order to make the plugin load faster, I've replaced it with tsconfig-paths.

**Comment by PaulPCIO** [comment]
is it possible to have the root point to an alias eg;
```html
<img src="myImage.svg" />
```
point to 
```text
.public/myImage.svg
```

tried playing around with the `gutterpreview.paths` as well as the `tsconfig.json` to no avail.

**Comment by tanghongxin** [comment]
> Sorry for the inconvenience, I'll update the docs.
> 
> It's been a while since I've adjusted that part of the code, as far as I can tell, the possibility to configure this with jsconfig was removed together with the typescript dependency.
> In order to make the plugin load faster, I've replaced it with tsconfig-paths.

It's strange to replace jsconfig.json with tsconfig.json in a pure javascript project just for a specific extension. 
I would say it's not universal.
