### ISSUE TITLE
hover image not show image size

### ISSUE THREAD

**Issue by zhiqiang21** [kisstkondoros/gutter-preview#8]
i see change log find 

>Add info about image size to hover preview

but after i install this plugin , when i hover image  src  ,it not show image size

**Comment by kisstkondoros** [comment]
Any further details? At least a screenshot would be nice...

**Comment by zhiqiang21** [comment]
i use for this, it's  not show image size 

![](https://ws1.sinaimg.cn/large/006tKfTcly1fgzhd1uzmmj31a60iw76u.jpg)

**Comment by kisstkondoros** [comment]
Closed because of missing information.
