### ISSUE TITLE
Compatible issues for vs code '1.39.2'

### ISSUE THREAD

**Issue by ViviZhou160916** [kisstkondoros/gutter-preview#81]
Hi,
I downloaded image preview extends from market link  https://marketplace.visualstudio.com/items?itemName=kisstkondoros.vscode-gutter-preview. But when I install it on my vs code 1.39.2 it shows the error **Unable to install extension 'kisstkondoros.vscode-gutter-preview' as it is not compatible with VS Code '1.39.2'.**
![image](https://user-images.githubusercontent.com/28652287/79105749-d8e13300-7da3-11ea-86cf-40369f24d72b.png)

**Comment by kisstkondoros** [comment]
The API baseline is 1.40.0 for this extension. Please upgrade vscode (1.44.0 is the latest version at the moment).

**Comment by kisstkondoros** [comment]
The API baseline was just raised to 1.44.0, I've thought it might be interesting for you.
Sorry if this causes any inconvenience, but I had to update...
