### ISSUE TITLE
Cannot found hugo images

### ISSUE THREAD

**Issue by kulti** [kisstkondoros/gutter-preview#82]
I'm using [hugo](https://gohugo.io/) static site generator.

[The static files](https://gohugo.io/content-management/static-files/
) are served on the site root path (eg. if you have the file static/image.png you can access it using http://{server-url}/image.png

It means that all paths to images is written without "/static" prefix. So gutter-preivew cannot found it.

How about to add search-paths setting? Maybe, it's possible to extend "paths" settings with "" (empty) or "default" alias to do that job.

Thank you for great extension.

**Comment by kisstkondoros** [comment]
Thanks for reaching out!

Could this be solved by setting ```gutterpreview.sourceFolder:"static"```?

**Comment by kulti** [comment]
Exactly I want to! Thank you.

By the way, hugo allows to use several static folders and different folders for different languages. But I don't think that that extension should support it.
