### ISSUE TITLE
How to config for previewing the url which contains the webpack alias

### ISSUE THREAD

**Issue by BruceLanCode** [kisstkondoros/gutter-preview#86]
How to config for previewing the url which contains the webpack's alias

eg:

```html
<img src="~@/assets/images/home/logo.png" alt="" class="logo" />
```

**Comment by kisstkondoros** [comment]
Should work with `gutterpreview.paths":{"~@/assets":"path/to/assets/from/root" }`

**Comment by Minori-ty** [comment]
hi，how to use with vite alias?

**Comment by LIiErkang** [comment]
> 

not work
