### ISSUE TITLE
Larger image previews on hover

### ISSUE THREAD

**Issue by ripperdoc** [kisstkondoros/gutter-preview#87]
Great little addon! Is it possible to make the image previews bigger, I imagine it could be a custom setting?

**Comment by kisstkondoros** [comment]
There is already a setting for it
"gutterpreview.imagePreviewMaxHeight"

**Comment by ripperdoc** [comment]
Doh, thanks! When I test that though, an improvement could be to not zoom in on images that are already smaller than the preview height, e.g. an image that is 50px high will be zoomed to fit 200px height, which looks bad on e.g. icons. It feels implied by "MaxHeight" that it will not zoom if the image is smaller, rather that it will not become larger than the given height? Just a suggestion, and again, thanks!
