### ISSUE TITLE
Spaces in image filename support

### ISSUE THREAD

**Issue by giddev** [kisstkondoros/gutter-preview#88]
I noticed the extension doesn't show a preview if the image name has spaces in it. 

The result is the following code won't display a preview

`[Image 1](my%20file%20name.png)`

Renaming the file and replacing spaces with "-" and regenerating the reference to 

`[Image 1](my-file-name.png)`

and it works.

**Comment by kisstkondoros** [comment]
Thanks for reporting this problem,

This seems to be related to #83, please refer to that for further details.

TLDR; known issue, I have no time to provide a fix for it, PR is appreciated.

Again, thanks for reporting it, and sorry for the inconvenience.
