### ISSUE TITLE
gutter-preview not working in python?

### ISSUE THREAD

**Issue by Schizo** [kisstkondoros/gutter-preview#90]
I have a python file that has bunch of comments to images, that I want to preview. However it seems like the image preview doesn't like either the python files or pylint. There is a brief "loading" message when I hover but than it is being replaced by python linting hints.

Thoughts?

**Comment by kisstkondoros** [comment]
If the problem is still present please file a new issue with more details about the workspace structure, list of active extensions and really anything that you think might help. Thanks
