### ISSUE TITLE
CPU spins for a long time on big projects

### ISSUE THREAD

**Issue by skamansam** [kisstkondoros/gutter-preview#92]
I don't really have any debug for this issue, but I have a medium-sized django project, with a vue frontend. After a while of using VSCode, this extension maxes out the CPU and doesn't stop even after hours of non-use, such as overnight.
Here is a screenshot of `htop` that shows the cpu usage.
![Screenshot from 2020-08-27 16 57 43](https://user-images.githubusercontent.com/102971/91494282-987fde80-e886-11ea-8a0b-d0cb0447ce3a.png)
If it's any help, I tend to leave my session running for days or even weeks at a time. I run VSCode and Vivaldi, and pretty much no other desktop apps. This has been happening for a few months that I know of, maybe longer, regardless of which desktop environment I use (i3, gnome, or kde/plasma).

**Comment by skamansam** [comment]
Also of note, I have had issues with compositing in the browser (i have an intel on-chip GPU instead of a discrete GPU). Some sites work really well and some sites will slow down or even cause the browser to become unresponsive due to heavy CSS compositing or other rendering issues. This may be an issue of compositing for electron, but I have no idea how to determine that.

**Comment by kisstkondoros** [comment]
I've been looking around to figure out what could have caused this for you, but I have no idea.

Maybe try to collect some more data based on https://github.com/Microsoft/vscode/wiki/Performance-Issues and open a new issue with those details.
