### ISSUE TITLE
Suggest: add  imagePreview Max Width

### ISSUE THREAD

**Issue by Jackiexiao** [kisstkondoros/gutter-preview#94]
In some case,  Max Width is useful than Max Height

**Comment by yuis-ice** [comment]
+1 yes. I want to have full sized image previewing support

**Comment by kisstkondoros** [comment]
Better late than never I guess.

The property "gutterpreview.imagePreviewMaxWidth" can be used to set an arbitrary width for the image preview

```json
"gutterpreview.imagePreviewMaxWidth": 300
```

Version 0.29.0 was just released which contains this.
