### ISSUE TITLE
Add setting to enable plugin on hover only

### ISSUE THREAD

**Issue by FujiMakoto** [kisstkondoros/gutter-preview#95]
For some projects which may have a long list of remote GIF URL's and such, this plugin can cause issues. It would be nice if we could just use the plugin to preview images on hover, and only have those images load and cache when they are hovered over instead of immediately when the code file is loaded.

**Comment by kisstkondoros** [comment]
Valid point, but with the many workarounds I have to use already because of the limitations implied by the environment... I think I can not do this.

However there is 'gutterpreview.showImagePreviewOnGutter' which one can turn off to avoid the heavy lag caused by the gifs at least
