### ISSUE TITLE
Adobe SVG image preview is not working it's not showing image

### ISSUE THREAD

**Issue by vamsee9** [kisstkondoros/gutter-preview#96]
### Please take look at this picture
![Screenshot (177)](https://user-images.githubusercontent.com/46225107/97857266-78a3e580-1d23-11eb-82c9-88c41cc6c4ca.png)

**Comment by kisstkondoros** [comment]
I believe that the svg (https://raw.githubusercontent.com/OpenNxt/TechEdu/main/assets/images/TechEdu.svg) is not valid.
