### ISSUE TITLE
tsconfig paths stopped working after 26.0.1

### ISSUE THREAD

**Issue by vxna** [kisstkondoros/gutter-preview#98]
![Untitled-2](https://user-images.githubusercontent.com/30002276/98983542-f8a32a00-2531-11eb-8d3a-598dd30c4602.jpg)

**Comment by DeveloperBlue** [comment]
Previews not working in 0.30.0 as well

Example with and without aliasing:
![Code_KZmGe5aQFS](https://user-images.githubusercontent.com/11480933/154974813-4ccb7e09-b03f-45f4-8c07-72862d1900c2.png)

tsconfig.json:
![Code_G9jqb5tJgz](https://user-images.githubusercontent.com/11480933/154974972-93d505c9-1920-4a23-9942-7c8bb1df3b7c.png)

**Comment by lisonge** [comment]
me too
