### ISSUE TITLE
Gutter import files.associations [feature request]

### ISSUE THREAD

**Issue by djmisterjon** [kisstkondoros/gutter-preview#99]
Hi friend,
i dont know if is possible but am asking myself if we can get gutterIcon for imports based on files associations
![image](https://user-images.githubusercontent.com/24865815/99151426-19ba6680-2669-11eb-9941-2a7f36c7b0a2.png)

Here the sketch , in this case, let say i have custom icons formats with `material-icon` themes.
```json
  "material-icon-theme.files.associations": {
    "*.bundles.js": "Webpack",
    "*.setting.js": "Tune",
    "*.data.js": "Database",
    "*.cmd.js": "Csharp",
    "*.func.js": "Fortran",
    "*.store.js": "Stylus"
  },
```
and by adding a flag, maybe  like `_importIconFileAssociation:true,`  to try get current theme icon from the files imported.
With `Parcel` we can import many type of files, and also with material-icon allow us to customize all icon with name.
Result can look like this .
![image](https://user-images.githubusercontent.com/24865815/99151535-f7751880-2669-11eb-9b03-631e7623fff5.png)

or maybe a config setting similar to `material-icon` for add manually some gutter imports decorations ? 
```json
  "gutterpreview.importFileAssociations": {
    "*.bundles.js": "Webpack",
    "*.setting.js": "Tune",
    "*.data.js": "Database",
    "*.cmd.js": "Csharp",
    "*.func.js": "Fortran",
    "*.store.js": "Stylus"
  }
```
what do you think ? is a good idea ?

**Comment by kisstkondoros** [comment]
I feel that this exceeds the scope of this extension. 

The idea itself is good though. I'm sure people would find it useful!
Perhaps make a new extension out of it yourself, there are plenty of resources out there to get started! :-)
